"""
get_activity
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from airflow.models import Variable
from astro import sql as aql
import pandas as pd
import pendulum

from airflow.models import Variable
import requests

@aql.dataframe(task_id="fetch_activity")
def fetch_activity_func():
    r = requests.get(Variable.get('API'))
    return r.json()
    print("Hello Airlfow")

@aql.dataframe(task_id="print_activity")
def print_activity_func(fetch_activity: pd.DataFrame):
    print(fetch_activity)

default_args={
    "owner": "mr.vrbabu@hotmail.com,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2025-02-13", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "mr.vrbabu@hotmail.com": "mailto:mr.vrbabu@hotmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm730orxl03di01jxqt60hjdr/cloud-ide/cm7330uyx03tt01il3moto4n3/cm7331juu03u201il2kq0tl5s",
    },
)
def get_activity():
    fetch_activity = fetch_activity_func()

    print_activity = print_activity_func(
        fetch_activity,
    )

dag_obj = get_activity()
